# Generated by Django 5.0.4 on 2024-10-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='planned_duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
